### ISSUE TITLE
Error at guildMember.js

### ISSUE THREAD

**Issue by XtraHottt** [Cudiph/monotonebot#2]
```
(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'goodbyeMessage' of null
at BotClient.<anonymous> (/app/events/guildMember.js:37:21)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

It also sends the same error with `welcomeMessage`

**Comment by Cudiph** [comment]
It happens because the guildsettings document in the database has not been created yet. Usually when you're starting the bot and send a message on a channel when the bot is ready or changing the guild configuration related command such as changing prefix, the bot will find the configuration and create a new one if it doesn't exist. So I thought it would be fine if I didn't add more checking, but I'll make a patch for this.
